version: 1
services:
  - type: web
    name: bartexcraft-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MP_ACCESS_TOKEN
        sync: false
      - key: WEBHOOK_URL
        value: https://bartexcraft-backend.onrender.com
      - key: SITE_URL
        sync: false
      - key: PORT
        value: 3000
